dist: xenial

install:
  - docker run --privileged --rm tonistiigi/binfmt --install all
  - docker buildx create --name xbuilder --use
  - docker buildx install

services:
  - docker


before_install:
  - GIT_TAG=$(git describe --long --tags --dirty --always)
  - DOCKER_REPO="sourcecodeai/ambience"
  - BASE_TAG=base-${GIT_TAG}
  - IMAGE_TAG=latest
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

stages:
  - build


jobs:
  include:
    - stage: build
      if: (branch = master) OR (branch = dev)
      script:
        - cd ./aura && docker buildx build --platform=linux/amd64,linux/arm64 --target aura-full --push -t ${DOCKER_REPO}:base -t ${DOCKER_REPO}:${BASE_TAG} . && cd ..
        - docker buildx build --platform=linux/amd64,linux/arm64 --build-arg basetag=${BASETAG} --push -t ${DOCKER_REPO}:${IMAGE_TAG} .
